---
swagger: "2.0"
info:
  description: "Api Documentation"
  version: "1.0"
  title: "Api Documentation"
  termsOfService: "urn:tos"
  contact: {}
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0"
host: "localhost:8080"
basePath: "/"
tags:
- name: "basic-error-controller"
  description: "Basic Error Controller"
- name: "ldap"
  description: "Ldap"
paths:
  /ldap/user:
    get:
      tags:
      - "ldap"
      summary: "search"
      operationId: "searchUsingGET"
      produces:
      - "*/*"
      parameters:
      - name: "fName"
        in: "query"
        description: "fName"
        required: false
        type: "string"
      - name: "lName"
        in: "query"
        description: "lName"
        required: false
        type: "string"
      - name: "username"
        in: "query"
        description: "username"
        required: false
        type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/LdapUser"
        "401":
          description: "Unauthorized"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
definitions:
  LdapUser:
    type: "object"
    properties:
      creationDate:
        type: "string"
      departmentId:
        type: "string"
      emailAddresses:
        type: "array"
        items:
          $ref: "#/definitions/LdapUserPhone"
      fname:
        type: "string"
      language:
        type: "string"
      lname:
        type: "string"
      uid:
        type: "string"
      workEmail:
        type: "string"
    title: "LdapUser"
  LdapUserPhone:
    type: "object"
    properties:
      type:
        type: "string"
      val:
        type: "string"
    title: "LdapUserPhone"
